#!/usr/bin/env bash
#install load balancer

sudo apt -y update
sudo apt -y install haproxy
printf %s "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
    balance roundrobin
    server 3290-web-01 35.237.241.192 check
    server 3290-web-02 34.139.46.240 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
