#!/usr/bin/env bash
#cript that pings an IP address passed as an argument
#Ping the IP 5 times

if [ "$#" != 1 ]
then
    echo  "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$*"
fi
