#!/usr/bin/env bash
# Bash script that

touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
	trap 'rm /var/run/myscript.pid; exit' SIGQUIT
done
