#!/usr/bin/env bash
# Displays Best School 10 times.

i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		5)
			echo "bad luck from China";;
		10)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	((i++))
done
