#!/usr/bin/env bash
# Let's install the ufw firewall
#Configure ufw so that it blocks all incoming traffic except the following TCP ports:
#22 (SSH)
#80 (HTTP)
#443 (HTTPS)

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
