#!/usr/bin/env bash
#Write a Bash script that configure a localhost resolves to 127.0.0.2

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8        facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
