#!/usr/bin/env bash
#script to run nginx as the nginx user
pkill apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
